### ISSUE TITLE
Implement way to delete courses

### ISSUE THREAD

**Issue by skiadas** [skiadas/HanoverEvals#110]
A course should be "marked" as deleted, instead of actually being removed. This way our migration scripts that bring data from Jenzabar will know not to recreate the course.

We need to add checks in various places to not have "removed" courses show up.
Removing a course should also unlink all the students and faculty from it.

An alternative to allowing a course to be deleted is to create a new state, "Frozen". Courses can be put in that state, and faculty will see them as frozen, and students will not see them at all. @altermattw thoughts? Perhaps a question for Elsa/Dawn.

**Comment by altermattw** [comment]
That sounds like a good plan.  The only possible problem I could foresee is if somehow, a large number of courses were automatically and erroneously generated (or perhaps imported from Jenzabar incorrectly).  Even then, the costs in terms of extra data to be stored would be minimal.  I think the benefits of the “frozen” status outweigh the possible risks of permanently deleting a course we decide later should have been kept.

On Jul 6, 2016, at 12:08 AM, Haris Skiadas <notifications@github.com<mailto:notifications@github.com>> wrote:


A course should be "marked" as deleted, instead of actually being removed. This way our migration scripts that bring data from Jenzabar will know not to recreate the course.

We need to add checks in various places to not have "removed" courses show up.
Removing a course should also unlink all the students and faculty from it.

An alternative to allowing a course to be deleted is to create a new state, "Frozen". Courses can be put in that state, and faculty will see them as frozen, and students will not see them at all. @altermattw<https://github.com/altermattw> thoughts? Perhaps a question for Elsa/Dawn.

**Comment by skiadas** [comment]
Hm offer them two options "freeze" and "delete". Freezing marks the course as inactive, deleting removes it and makes it subject to reappear on the next jenzabar migration, so should be used only on "erroneous" courses.

**Comment by skiadas** [comment]
Hm, not sure why I didn't close this with recent commits. I guess it was a duplicate of #71
