### ISSUE TITLE
Changing instructor in admin/section/edit does not persist

### ISSUE THREAD

**Issue by altermattw** [skiadas/HanoverEvals#114]
Deleting the instructor on this page removes them from the section, but it is not possible to add them back or to add a new instructor so that it persists after pressing Submit.

**Comment by altermattw** [comment]
Tags are also not persisting after being added.

**Comment by skiadas** [comment]
This was subtle, let me explain what happened. We had the following code in typeaheadCollection.js:

```
      $insertedEl = $(prototype.replace(/__name__/g, count)
            .replace(/__value__/g, obj.value))
         .addClass('deletable btn btn-primary')
         .appendTo($target);
      $('input', $insertedEl).val(obj.id);
```

So the first 4 lines create the new `$insertedEl` component, and set some parameters to it, then save it in the `$insertedEl` variable. The last line looks for the input in that variable, and sets its value. I could not do that via "replace" because of some escaping that needed to be done, that "val" would do for me.

When you wanted to add the x buttons, which look great btw, you added two more steps to the long chain that defined `$insertedEl`:
```
      $insertedEl = $(prototype.replace(/__name__/g, count)
            .replace(/__value__/g, obj.value))
         .addClass('deletable btn btn-primary')
         .appendTo($target)
         .children('div')
         .append(deleteIcon);
      $('input', $insertedEl).val(obj.id);
```

But these extra steps changed the $insertedEl to be its children, and input could no longer be found. The id of the newly created elements was not being set properly, so they weren't recognized on submission. I should have not tried to chain $insertedEl so much to avoid such problems. Lesson learned.
