### ISSUE TITLE
Some UI thoughts

### ISSUE THREAD

**Issue by skiadas** [skiadas/HanoverEvals#129]
@altermattw Just throwing some stuff out there.

- [ ] We should establish some consistency in where things are found. Should all actions appear as buttons on the main lists? Should most be hidden behind "clicking" the specific item? It's somewhat mixed right now.
- [ ] We should consider using icons for most action buttons, for compactness.

**Comment by altermattw** [comment]
Could you say more about the first point?  In terms of clickables, we've got buttons and hyperlinks now, but those seem to be pretty adaptive.  I don't think it would improve things to turn all the hyperlinks (e.g., names of instructors) into buttons.  Or were you thinking more of changing the menu structure?  Something else?

I think icons would be a good idea if we start running short on screen real estate, but I worry that they may add some confusion because most users will be using the system infrequently.  For example, the "Complete Now!" button is nice and unambiguous for students.  I'm not sure if there is a good icon for "Roster."  For the UI for frequent users, like an IR person or faculty, I think we could use more icons.  If our query system begins to get complex and has lots of action options, I think icons would be a great idea.

**Comment by skiadas** [comment]
Well I'm thinking of for instance the Department tab vs the Section tab. The department tab has a clickable name that takes you to the edit page, while the section tab has a "edit" action button instead. (and the add-new-department link needs to be buttonized probably). Then Terms has a clickable x for deleting, but for the section/department/question menus that I just added a delete option, I did so by adding a button to their "edit" pages. I just feel we need some more consistency.

I'm mostly talking about the various admin pages at this point.

For the icons idea I guess I just find some of the buttons big at this point. Perhaps if we made them smaller it wouldn't bother me much. But maybe it only bothers me, in which case it's fine. I think we could use the various glyphicons for many actions though, for instance roster could be glyphicon-user or glyphicon-th-list, edit could be the pencil, adding a new item could be some sort of plus sign next to the heading, etc.

**Comment by skiadas** [comment]
I'm gonna go ahead and close this, as I think you've implemented most of it.

What do you think about using a plus icon for creating new items?

**Comment by altermattw** [comment]
Thought about it, but in most contexts, I wasn't confident that it would be clear what it did. Most of the time, the add buttons appear at the top, only once per page, so little savings in switching to an icon. I'll take another look, though.

Bill

Sent from my iPhone

On Jul 15, 2016, at 9:35 PM, Haris Skiadas <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm gonna go ahead and close this, as I think you've implemented most of it.

What do you think about using a plus icon for creating new items?

-
