### ISSUE TITLE
"add choice" button not working on tableForm branch 

### ISSUE THREAD

**Issue by altermattw** [skiadas/HanoverEvals#140]
I created a new branch called "tableForm" to experiment with presenting some parts of the forms as tables.  For questions, my strategy was to focus on questions with choices and put the choices into a table.  It looks better.  The problem is that the "Add choice" button no longer adds a new choice.  One way to solve this is to have the "Add choice" button trigger the creation of a new choice with numValue and textValue set to null, and then re-render the page.  That should display a new (blank) row in the table.

**Comment by skiadas** [comment]
Nah it should be simpler than that. We'll need to adjust the creation of the prototype and possibly the javascript on the page.

**Comment by skiadas** [comment]
@altermattw If you look at this: https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Twig/Resources/views/Form/form_div_layout.html.twig

around line 20 or so it shows how the data-prototype attribute is introduced into compound widgets. Since we are laying out the form manually, we are bypassing that particular snippet, so we'll have to do the corresponding work manually.

This way the top element of the table should end up having a `data-prototype` property, and we can adjust our script that handles the click of the "add" to do the right thing with that prototype.

**Comment by altermattw** [comment]
Thanks, Haris.  I've been working on it and teaching myself the twig block conventions.  Here's the section:
```
{%- block collection_widget -%}
    {% if prototype is defined %}
        {%- set attr = attr|merge({'data-prototype': form_row(prototype) }) -%}
    {% endif %}
    {{- block('form_widget') -}}
{%- endblock collection_widget -%}

```
That looks like it checks to see if it has received a 'prototype' variable and, if so, either adds a new 'data-prototype' attribute with value 'form_row(prototype)' or, if 'data-prototype' is already an attribute, replaces the existing 'data-prototype' attr with form_row(prototype).

Things still to figure out:

1. What do {%- and {{- indicate?
2. How does the prototype of a set of DOM elements help us?  I'll read more about prototypes.

**Comment by altermattw** [comment]
Aha!  Page 20 of the Twig book says that "-" is whitespace control.  Got it.  On to prototypes.

**Comment by altermattw** [comment]
This page looks handy for dynamically adding new elements:
http://symfony.com/doc/current/cookbook/form/form_collections.html

**Comment by skiadas** [comment]
Yep that's the page. We have the javascript part implemented already, the relevant javascript is part of that page (app/Resources/views/admin/question/edit.html.twig) lines 20 through 32.

Basically the prototype is a template for how new items should look like, and it's stored as a data attribute at the top level item of the collection by default. Then when the javascript code needs to add a new item, it reads the prototype from that top level item, alters it to represent new values, and inserts it in the DOM.

Since we manually created the top level element of the collection, there is no prototype set on it.

**Comment by altermattw** [comment]
I've got it to print the prototype information into the `<tbody>` tag that sets off all the rows of the table, but I think the prototype isn't working because it's still coming out as `<div>`s instead of `<tr>`s:

`<tbody class="choices" data-prototype="<div id=&quot;form_choices___name__&quot; class=&quot;choice&quot;><div class=&quot;form-group&quot;><label class=&quot;control-label required&quot; for=&quot;form_choices___name___numValue&quot;>Num value</label><input type=&quot;text&quot; id=&quot;form_choices___name___numValue&quot; name=&quot;form[choices][__name__][numValue]&quot; required=&quot;required&quot; class=&quot;toggleable form-control&quot; /></div><div class=&quot;form-group&quot;><label class=&quot;control-label required&quot; for=&quot;form_choices___name___textValue&quot;>Text value</label><input type=&quot;text&quot; id=&quot;form_choices___name___textValue&quot; name=&quot;form[choices][__name__][textValue]&quot; required=&quot;required&quot; class=&quot;toggleable form-control&quot; /></div><div class=&quot;form-group&quot;><button type=&quot;button&quot; id=&quot;form_choices___name___delete&quot; name=&quot;form[choices][__name__][delete]&quot; class=&quot;toggleable deleteButton btn&quot;>Remove</button></div></div>">`

My guess is that to make use of the prototype approach to new elements, we will need to do the templating further upstream. What do you think?  If yes, do you know where I would look to change the template that the data-prototype is generating?

**Comment by skiadas** [comment]
Yeah this is a tricky one and not too well explained in the docs. Basically the prototype is using the same format as the elements. The problem is that you are not letting the elements form by themselves, so exactly it's a question of doing this further "upstream". What you can do is "overwrite" any of those named blocks, but somehow localized to that file. I think this is described here: http://symfony.com/doc/current/cookbook/form/create_form_type_extension.html#override-the-file-widget-template-fragment

And I think a close approach is here: http://symfony.com/doc/current/cookbook/form/create_custom_field_type.html

You can see a little bit of it in the typeahead widget implementation, the relevant twig part is in app/Resources/views/form/typeahead.html.twig
where I am specifying the widgets for various custom field types, that essentially inherit from the standard types but are formatted differently.

**Comment by altermattw** [comment]
Eureka!
I think the key is to add getBlockPrefix to the end of the collection types we want to render as table rows:  OrderedQuestionType and QuestionChoiceType.  The prefix is "tableFormCollection."  Then, create a form template file in views/form that over-rides the tableFormCollection row.  Finally, we add a line to config.yml under Twig form_themes to read the form template.  I got some very simple text to render and will now try to get actual form fields.

**Comment by altermattw** [comment]
My current challenge is to implement separate templates to render (1) the beginning and end of the table, with a label that applies to the collection as a whole (e.g., "Choices"), and (2) the rows of the table, which are based on the children of the collection.  One way to do this is to create an extension of CollectionType, maybe called TableFormCollectionType, with its own getBlockPrefix ("tableFormCollection") and change the getBlockPrefix for OrderedQuestionType and QuestionChoiceType to something like "rowForm", since those two are not actually collections but will instead be rows of a table.  Then I will write one template for tableFormCollection that begins and ends the table, and another template for rowForm that has the `<tr><td>element1</td><td>element2</td></tr>` structure.  A related challenge is how to access the children of a collection when you do not know their name.  I would like to just iterate over them, but I'm not sure how to access each part without knowing how many parts there are.  Perhaps I could just use indexing?

**Comment by altermattw** [comment]
Above approach is not quite right. I don't think we should assign getBlockPrefix both for Collections and for their elements.  Instead, just do getBlockPrefix for the Collection, and access the elements from inside the template for the Collection.

**Comment by skiadas** [comment]
Don't you need to provide a separate template for the elements and the prototype? To tell them to render like table rows instead of their normal behavior?

**Comment by altermattw** [comment]
I think I will render the Choices differently from the Tags, so I'm changing course slightly.  Instead of trying to create one collection that can store either choices or tags (which was causing lots of problems), I'm going to create two new separate collections, one for tags and one for choices.  I'll try applying the steps in the "Collection of Forms" example to each of those.

**Comment by altermattw** [comment]
Hold everything.  Maybe I can do the whole thing by customizing the prototype:  [link](http://symfony.com/doc/current/cookbook/form/form_customization.html#cookbook-form-custom-prototype)

**Comment by skiadas** [comment]
Sorry, I've been taking a break from everything for the last week or so. About to get back to it. Let me know if there's something I can do, or if you wanted to meet at some point. That link does look useful.

**Comment by altermattw** [comment]
No problem.  I’ve had some side projects, too, that have intruded.  Just made some good progress on the Question Edit form.  Will commit soon, then see if I can do the same with tags.

—Bill

On Jul 27, 2016, at 11:43 AM, Haris Skiadas <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry, I've been taking a break from everything for the last week or so. About to get back to it. Let me know if there's something I can do, or if you wanted to meet at some point. That link does look useful.

**Comment by altermattw** [comment]
Abandoned tableForm branch and making commits directly to symfony branch.
