### ISSUE TITLE
Improve the query system

### ISSUE THREAD

**Issue by skiadas** [skiadas/HanoverEvals#179]
- [x] don't save without a name
- [x] add dynamically generated description of what the query does
- [x] Try to remove the non-needed templates
- [x] add ability to delete saved queries
- [x] Only show useful options on case filter list
- [x] Use correct result counts for courses with multiple instructors
- [x] Add target instructor infrastructure

**Comment by altermattw** [comment]
@skiadas, could you take a look at the js at the bottom of views/query/edit and see if that approach will work okay for modifying the look of the query forms?  Unfortunately, Bootstrap requires some changes to the DOM, rather than just CSS styling, so I don't see a good alternative without delving into the abyss of symfony forms.  I tried to anchor everything to IDs that should stay constant in the form.

**Comment by skiadas** [comment]
I think we can put these into the forms. Let me try to do what I think you are doing without using the Javascript, and we can make adjustments

**Comment by skiadas** [comment]
@altermattw Ok I think I managed to make it happen. Does the form look the way you intended?

**Comment by altermattw** [comment]
Outstanding!  I can see where you put that, so I'll try to use that approach if there are further <div> additions.
