### ISSUE TITLE
Input tags rendering correctly?

### ISSUE THREAD

**Issue by altermattw** [skiadas/HanoverEvals#55]
In the evaluation form, *each* item has a hidden input that has no value attached to it; just a name:

`<input type="hidden" id="layout_answers_0_instructor" name="layout[answers][0][instructor]">`
  ...question details
`<input type="hidden" id="layout_answers_1_instructor" name="layout[answers][1][instructor]">`
  ...question details

The src/Form/Type/AnswerType file has these instructions:
```
$form->add('instructor', HiddenType::class, array('data' => $instrName));
if ($question->isTextType()) {
                $form->add('answer', TextareaType::class,
```
...

This makes me think that (1) the "add hidden field" is firing too many times; it should only need to be printed once, not for every item. (2) the instructor name is not being correctly propagated to the form. Instead, just the word "instructor" appears.

**Comment by skiadas** [comment]
It does need to be printed once for every question, and it holds the information of whether that question pertains to a specific instructor. For most of the questions the value is "null" and so it does not even show (but an input field is produced since there is a property in the corresponding "answer entity" that needs to be filled, even if the value is null. If you look at the question for the instructor, it should have a "value" for the input with the instructor's login.

We could in theory add a couple of lines of logic to the form to exclude these, but they don't really hurt any by being there. Let's leave the issue for now, but I don't think it's urgent.
