### ISSUE TITLE
Improve look and feel of typeahead element

### ISSUE THREAD

**Issue by skiadas** [skiadas/HanoverEvals#97]
@altermattw I've been working on the last couple of days creating a field for selecting from a list of entity objects (e.g. list of instructors). You can look at it by switching to the typeahead branch and hitting the "/test" route on the browser. You can choose to add items either by searching them from the box or by picking them up from the pulldown.

 Currently you can delete an element from the formed list by just clicking on it. Ideally:

- [ ] There would be a button or something created on each item, or appearing when we hover.
- [ ] Hovering over the items would somehow gently emphasize them.
- [ ] The item would only be deleted on clicking on the button.
- [ ] There's also some alignment issues with the typeahead field. You can read more about the problem at https://github.com/bassjobsen/Bootstrap-3-Typeahead (I'm actually using Twitter's typeahead instead of the one mentioned in that link, but he talks about the problem with that).

You're probably more of an expert on how to get that going. The key places to work with would be the `app/Resources/views/form/typeahead.html.twig` file and the `web/js/typeaheadCollection.js` file.

**Comment by altermattw** [comment]
The twitter typeahead.js appears to have a problem with some hard-coded in-line styling, as discussed [here](https://github.com/twitter/typeahead.js/issues/378). 
One problem is the alignment of the drop-down button and the text input. That can be fixed by removing the float:left style from the text input element.  This could be done in typeahead.html.twig by adding:
`style="float:none"`
The shortening of the text field is controlled by the enveloping <span> tag that has the "twitter-typeahead" class, which adds `display: inline-block`. Changing that to `display:block` fixes the width problem.

**Comment by skiadas** [comment]
Make whatever changes you need.

**Comment by altermattw** [comment]
Uh-oh.  This is looking bad again, both on admin/roster and admin/section. What happened?

**Comment by altermattw** [comment]
It would be nice to have the suggestions/hints have an opaque background. Right now they can run into the text below the input field. [This page](http://stackoverflow.com/questions/20198247/twitters-typeahead-js-suggestions-are-not-styled-have-no-border-transparent-b) discusses the issue. 
The javascript we're using for typeahead is [version 0.11.1 from twitter](http://twitter.github.io/typeahead.js/releases/latest/typeahead.bundle.js), and the CSS is [version 2.3 from hyspace](https://github.com/hyspace/typeahead.js-bootstrap3.less). Perhaps they are not completely compatible?

**Comment by altermattw** [comment]
I think the typeahead styling has now been resolved. Still need to work out how to deal with different functions of typeahead for new questions added to a tag vs. for instructors or tags added to a section.
